"""
Pydantic schemas for Product API requests and responses.
"""

from datetime import datetime
from decimal import Decimal
from pydantic import BaseModel, Field, ConfigDict


class ProductBase(BaseModel):
    # Shared product fields used by both creation and response schemas.
    name: str = Field(..., min_length=1, max_length=255, examples=["Wireless Earbuds"])
    category: str | None = Field(None, max_length=100, examples=["Electronics"])
    price: Decimal = Field(..., gt=0, decimal_places=2, examples=[29.99])
    image_url: str | None = Field(None, examples=["https://placehold.co/400x400"])
    description: str | None = Field(None, examples=["High-quality wireless earbuds"])


class ProductCreate(ProductBase):
    """
    Schema for creating a new product.

    Inherits all fields from ProductBase.
    No additional fields needed — the database generates id and created_at.
    """
    pass


class ProductResponse(ProductBase):
    """
    Schema for returning a product in API responses.

    Adds id and created_at which are generated by the database.

    """
    id: int
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class ProductList(BaseModel):
    """
    Paginated product list response.

    Example response:
    {
        "products": [...],
        "total": 100,
        "page": 1,
        "per_page": 20
    }
    """
    products: list[ProductResponse]
    total: int
    page: int
    per_page: int